_wandb:
    value:
        cli_version: 0.26.0
        e:
            drqecg2vdnjp1uapprnjedmze6c1pngv:
                codePath: src\ml26\proyectos\CarRacing\wandbTest.py
                codePathLocal: src\ml26\proyectos\CarRacing\wandbTest.py
                cpu_count: 12
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1023178436608"
                        used: "316018126848"
                email: floresgalindog@gmail.com
                executable: C:\Users\NiggaChain\Documents\GitHub\ML26_PXNDX_MADERO\.venv\Scripts\python.exe
                git:
                    commit: b1a5e91a45a8de2cb5246cbefe5772fb1da4db1d
                    remote: https://github.com/Derek-Bltrn/ML26_PXNDX_MADERO.git
                host: PXNDX_Services
                memory:
                    total: "16907755520"
                os: Windows-11-10.0.26200-SP0
                program: c:\Users\NiggaChain\Documents\GitHub\ML26_PXNDX_MADERO\src\ml26\proyectos\CarRacing\wandbTest.py
                python: CPython 3.13.7
                root: C:\Users\NiggaChain\Documents\GitHub\ML26_PXNDX_MADERO
                startedAt: "2026-04-23T06:01:04.624353Z"
                writerId: drqecg2vdnjp1uapprnjedmze6c1pngv
        m: []
        python_version: 3.13.7
        t:
            "4": 3.13.7
            "5": 0.26.0
            "8":
                - 3
            "12": 0.26.0
            "13": windows-amd64
